'use strict';
const KEY='profit-land-v7',V5='profit-land-v5',V4='profit-land-v4',SNAP='profit-land-v7-snapshots',BACKUP='profit-land-last-file-backup';
const $=s=>document.querySelector(s),clone=o=>JSON.parse(JSON.stringify(o)),id=()=>Math.random().toString(36).slice(2)+Date.now().toString(36),money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(Number(n)||0))+' ₽';
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function periodIdFromDate(d=new Date()){const x=new Date(d);if(x.getDate()<9)x.setMonth(x.getMonth()-1);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`}
function periodDates(pid){const [y,m]=pid.split('-').map(Number);return{start:iso(new Date(y,m-1,9)),end:iso(new Date(y,m,8))}}
function nextPeriodId(pid){const [y,m]=pid.split('-').map(Number),d=new Date(y,m,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function periodLabel(pid){const [y,m]=pid.split('-').map(Number);return new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(new Date(y,m-1,9)).replace(/^./,c=>c.toUpperCase())}
function shortDate(s){return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit'}).format(new Date(s+'T12:00:00'))}
function defaultBudgets(){return{food:{couple:{name:'Мы с Тимохой',limit:2500},mom:{name:'Мама',limit:0}},social:{oksana:{name:'Оксана',limit:3000},tim:{name:'Тимоха',limit:0},mom:{name:'Мама',limit:0}},fixed:{housing:{name:'Квартира',items:[]},comm:{name:'Связь',items:[]},digital:{name:'Цифровое',items:[]},car:{name:'Машина / парковка',items:[]}}}}
function defaultBusiness(){return{operatingRate:30,taxRate:6,developmentRate:10,revenues:[],operatingExpenses:[],taxPayments:[],developmentExpenses:[],distributions:[],fixedItems:[{id:'ip-fixed-2026',name:'Фиксированные взносы ИП',amount:57390/12,active:true}],fixedPayments:[]}}
function newPeriod(pid=periodIdFromDate(),debts=[]){const d=periodDates(pid),openings={};debts.forEach(x=>openings[x.id]=+x.principal||0);return{id:pid,start:d.start,end:d.end,incomes:[],savings:[],expenses:[],fixedPayments:[],cashbacks:[],risks:[],emergencies:[],businessReturns:[],debtPayments:[],debtOpenings:openings}}
function defaults(){return{version:7,budgets:defaultBudgets(),debts:[],activePeriod:newPeriod(),archives:[],cashbackCarry:0,profitCarry:0,cashCarry:0,business:defaultBusiness()}}
function normalizePeriod(p,debts=[]){const n={...newPeriod(p?.id||periodIdFromDate(),debts),...(p||{})};for(const k of ['incomes','savings','expenses','fixedPayments','cashbacks','risks','emergencies','businessReturns','debtPayments'])if(!Array.isArray(n[k]))n[k]=[];if(!n.debtOpenings)n.debtOpenings={};n.incomes.forEach(x=>x.owner=x.owner||'Совместный');n.expenses.forEach(x=>{if(x.business==null)x.business=false;if(x.envelope==='food'&&!x.budgetWeek)x.budgetWeek=weekNumberForTimestamp(n,x.ts)});n.emergencies.forEach(x=>{if(x.business==null)x.business=false});n.debtPayments.forEach(x=>{if(!x.source)x.source='family'});return n}
function normalizeDebt(d){if(!d.scope)d.scope='family';if(d.rate==null){const base=Math.max(0,+d.principal||0),old=Math.max(0,+d.interestPerPeriod||0);d.rate=base?old/base*100:0;d.rateUnit='month'}if(!d.rateUnit)d.rateUnit='month';return d}
function normalizeBusiness(b){const d=defaultBusiness(),n={...d,...(b||{})};for(const k of ['revenues','operatingExpenses','taxPayments','developmentExpenses','distributions','fixedItems','fixedPayments'])if(!Array.isArray(n[k]))n[k]=clone(d[k]||[]);n.operatingRate=Number.isFinite(+n.operatingRate)?+n.operatingRate:30;n.taxRate=Number.isFinite(+n.taxRate)?+n.taxRate:6;n.developmentRate=Number.isFinite(+n.developmentRate)?+n.developmentRate:10;if(!n.fixedItems.length)n.fixedItems=clone(d.fixedItems);for(const x of n.fixedItems){if(x.active==null)x.active=true;x.amount=+x.amount||0}return n}
function migrateV4(v){const s=defaults();if(!v)return s;s.budgets=clone(v.budgets||s.budgets);for(const g of Object.values(s.budgets.fixed)){for(const item of g.items||[]){if(item.business==null)item.business=false;if(item.active==null)item.active=true}}s.cashbackCarry=+v.cashbackCarry||0;s.profitCarry=+v.profitVault||0;s.activePeriod=normalizePeriod(v.activePeriod||newPeriod(),s.debts);s.archives=(v.archives||[]).map(a=>({id:a.id||id(),closedAt:a.closedAt||Date.now(),period:normalizePeriod(a.period,s.debts),budgets:clone(a.budgets||s.budgets),debts:[],cashbackCarry:+a.cashbackCarry||0,openingProfit:0,periodResult:+a.closingProfit||0,closingProfit:+a.closingProfit||0}));return s}
function normalizeState(s){const d=defaults(),n={...d,...(s||{})};n.version=7;if(s?.cashCarry==null)n.cashCarry=+n.profitCarry||0;n.budgets=n.budgets||defaultBudgets();n.debts=(n.debts||[]).map(normalizeDebt);n.activePeriod=normalizePeriod(n.activePeriod||newPeriod(),n.debts);n.archives=(n.archives||[]).map(a=>({...a,period:normalizePeriod(a.period,n.debts),budgets:a.budgets||clone(n.budgets),debts:(a.debts||[]).map(normalizeDebt),openingCash:a.openingCash??a.openingProfit??0,closingCash:a.closingCash??a.closingProfit??0}));n.business=normalizeBusiness(n.business);return n}
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v)return normalizeState(v)}catch{}try{const v5=JSON.parse(localStorage.getItem(V5));if(v5){const s=normalizeState(v5);localStorage.setItem(KEY,JSON.stringify(s));return s}}catch{}try{const v4=JSON.parse(localStorage.getItem(V4));const s=normalizeState(migrateV4(v4));localStorage.setItem(KEY,JSON.stringify(s));return s}catch{}const s=defaults();localStorage.setItem(KEY,JSON.stringify(s));return s}
let state=load(),viewArchiveId=null,pageMode=localStorage.getItem('profit-land-page')==='business'?'business':'family',entryMode=null,editRef=null,fixedRef=null,debtRef=null,debtPayRef=null,businessEntryMode=null,businessEditRef=null,businessFixedRef=null;
function snapshot(){try{const a=JSON.parse(localStorage.getItem(SNAP)||'[]');a.push({ts:Date.now(),state:clone(state)});while(a.length>25)a.shift();localStorage.setItem(SNAP,JSON.stringify(a))}catch{}}
function save(){snapshot();state.version=7;localStorage.setItem(KEY,JSON.stringify(state));updateBackupStatus()}
function sum(a){return a.reduce((x,y)=>x+(+y||0),0)}
function safe(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1700)}
function weekNumberForTimestamp(p,ts){const start=new Date(p.start+'T00:00:00'),d=new Date(ts||Date.now()),days=Math.floor((d-start)/86400000);return Math.max(1,Math.min(4,Math.floor(Math.max(0,days)/7)+1))}
function currentBudgetWeek(p){return weekNumberForTimestamp(p,Date.now())}
function activeView(){if(viewArchiveId){const a=state.archives.find(x=>x.id===viewArchiveId);if(a)return{period:a.period,budgets:a.budgets,debts:a.debts||[],cashbackCarry:a.cashbackCarry||0,profitCarry:a.openingProfit||0,cashCarry:a.openingCash??a.openingProfit??0,archived:true,closingProfit:a.closingProfit||0,closingCash:a.closingCash??a.closingProfit??0,periodResult:a.periodResult||0}}return{period:state.activePeriod,budgets:state.budgets,debts:state.debts,cashbackCarry:state.cashbackCarry,profitCarry:state.profitCarry,cashCarry:state.cashCarry,archived:false}}
function incomeTotal(v){return sum(v.period.incomes.map(x=>x.amount))}function savingsPlan(v){return incomeTotal(v)*.1}function savingsFact(v){return sum(v.period.savings.map(x=>x.amount))}
function foodPlan(v){return sum(Object.values(v.budgets.food).map(x=>x.limit))*4}function socialPlan(v){return sum(Object.values(v.budgets.social).map(x=>x.limit))}
function activeFixedItems(v){return Object.values(v.budgets.fixed).flatMap(g=>g.items||[]).filter(x=>x.active)}function fixedPlan(v){return sum(activeFixedItems(v).map(x=>x.amount))}function fixedPaid(v){return sum(v.period.fixedPayments.map(x=>x.amount))}
function foodSpent(v){return sum(v.period.expenses.filter(x=>x.envelope==='food').map(x=>x.amount))}function socialSpentAll(v){return sum(v.period.expenses.filter(x=>x.envelope==='social').map(x=>x.amount))}function variableSpent(v){return foodSpent(v)+socialSpentAll(v)}function emergencySpent(v){return sum(v.period.emergencies.map(x=>x.amount))}
function debtById(v,idv){return (v.debts||[]).find(x=>x.id===idv)}function debtPaid(v,did){return sum(v.period.debtPayments.filter(x=>x.debtId===did).map(x=>x.amount))}function debtInterestPaid(v,did){return sum(v.period.debtPayments.filter(x=>x.debtId===did).map(x=>x.interestPart))}function debtPrincipalPaid(v,did){return sum(v.period.debtPayments.filter(x=>x.debtId===did).map(x=>x.principalPart))}
function daysInPeriod(p){const a=new Date(p.start+'T12:00:00'),b=new Date(p.end+'T12:00:00');return Math.max(1,Math.round((b-a)/86400000)+1)}
function debtOpening(v,d){return Number(v.period.debtOpenings?.[d.id]??d.principal??0)}
function debtInterestDue(v,d){const body=debtOpening(v,d),rate=(+d.rate||0)/100,days=daysInPeriod(v.period);if(d.rateUnit==='day')return body*rate*days;if(d.rateUnit==='year')return body*rate*days/365;return body*rate}
function rateLabel(d){const unit=d.rateUnit==='day'?'в день':d.rateUnit==='year'?'в год':'в месяц';return `${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:4}).format(+d.rate||0)}% ${unit}`}
function familyDebts(v){return(v.debts||[]).filter(d=>(d.scope||'family')==='family')}function businessDebts(v){return(v.debts||[]).filter(d=>d.scope==='business')}
function debtPlannedCost(v){return sum(familyDebts(v).filter(d=>d.active||debtPaid(v,d.id)>0).map(d=>Math.max(d.active?debtInterestDue(v,d):0,debtPaid(v,d.id))))}
function businessDebtPlannedCost(v=activeView()){return sum(businessDebts(v).filter(d=>d.active||debtPaid(v,d.id)>0).map(d=>Math.max(d.active?debtInterestDue(v,d):0,debtPaid(v,d.id))))}
function businessDebtPaidByBusiness(v=activeView()){return sum(v.period.debtPayments.filter(x=>debtById(v,x.debtId)?.scope==='business'&&x.source==='business').map(x=>x.amount))}
function businessDebtRemainingPlan(v=activeView()){return sum(businessDebts(v).filter(d=>d.active).map(d=>Math.max(0,debtInterestDue(v,d)-debtPaid(v,d.id))))}
function businessChargesPeriod(v){let n=0;n+=sum(v.period.expenses.filter(x=>x.business).map(x=>x.amount));n+=sum(v.period.emergencies.filter(x=>x.business).map(x=>x.amount));n+=sum(v.period.fixedPayments.filter(x=>x.business).map(x=>x.amount));n+=sum(v.period.debtPayments.filter(x=>x.business||((debtById(v,x.debtId)?.scope==='business')&&x.source!=='business')).map(x=>x.amount));return n}
function businessReturnsPeriod(v){return sum(v.period.businessReturns.map(x=>x.amount))}
function allPeriods(){return[...state.archives.map(a=>({period:a.period,budgets:a.budgets,debts:a.debts||[],archived:true})),{period:state.activePeriod,budgets:state.budgets,debts:state.debts,archived:false}]}
function businessDueTotal(){let c=0,r=0;for(const v of allPeriods()){c+=businessChargesPeriod(v);r+=businessReturnsPeriod(v)}return c-r}
function businessReturnsAll(){return sum(allPeriods().flatMap(v=>v.period.businessReturns.map(x=>x.amount)))}
function projectedVariableCost(v){return Math.max(foodPlan(v),foodSpent(v))+Math.max(socialPlan(v),socialSpentAll(v))}
function projectedResult(v){return incomeTotal(v)-savingsPlan(v)-projectedVariableCost(v)-fixedPlan(v)-emergencySpent(v)-debtPlannedCost(v)+businessReturnsPeriod(v)}
function closingResult(v){return incomeTotal(v)-savingsFact(v)-foodSpent(v)-socialSpentAll(v)-fixedPlan(v)-emergencySpent(v)-debtPlannedCost(v)+businessReturnsPeriod(v)}
function actualCashDelta(v){const familyDebtPaid=sum(v.period.debtPayments.filter(x=>x.source!=='business').map(x=>x.amount));return incomeTotal(v)-savingsFact(v)-variableSpent(v)-fixedPaid(v)-emergencySpent(v)-familyDebtPaid+businessReturnsPeriod(v)}
function projectedProfit(v){return(+v.profitCarry||0)+projectedResult(v)}function closingProfit(v){return(+v.profitCarry||0)+closingResult(v)}function cashFact(v){return(+v.cashCarry||0)+actualCashDelta(v)}
function cashbackBalance(v){return(v.cashbackCarry||0)+sum(v.period.cashbacks.map(x=>x.amount))-sum(v.period.risks.map(x=>x.amount))}
function currentWeekSpent(v,bucket,w){return sum(v.period.expenses.filter(x=>x.envelope==='food'&&x.bucket===bucket&&(x.budgetWeek||weekNumberForTimestamp(v.period,x.ts))===w).map(x=>x.amount))}
function socialSpent(v,bucket){return sum(v.period.expenses.filter(x=>x.envelope==='social'&&x.bucket===bucket).map(x=>x.amount))}
function businessRevenueTotal(){return sum(state.business.revenues.map(x=>x.amount))}
function businessOperatingSpentOwn(){return sum(state.business.operatingExpenses.map(x=>x.amount))+sum(state.business.fixedPayments.map(x=>x.amount))}
function businessOperatingSpentAll(){let familyPaid=0;for(const v of allPeriods())familyPaid+=businessChargesPeriod(v);return businessOperatingSpentOwn()+familyPaid}
function businessOperatingAllocated(){return businessRevenueTotal()*(+state.business.operatingRate||0)/100}
function businessTaxAllocated(){return businessRevenueTotal()*(+state.business.taxRate||0)/100}
function businessDevelopmentAllocated(){return businessRevenueTotal()*(+state.business.developmentRate||0)/100}
function businessOperatingBalance(){return businessOperatingAllocated()-businessOperatingSpentAll()}
function businessTaxBalance(){return businessTaxAllocated()-sum(state.business.taxPayments.map(x=>x.amount))}
function businessDevelopmentBalance(){return businessDevelopmentAllocated()-sum(state.business.developmentExpenses.map(x=>x.amount))}
function businessDistributionsTotal(){return sum(state.business.distributions.map(x=>x.amount))}
function businessCashNow(){return businessRevenueTotal()-businessOperatingSpentOwn()-sum(state.business.taxPayments.map(x=>x.amount))-sum(state.business.developmentExpenses.map(x=>x.amount))-businessDistributionsTotal()-businessReturnsAll()-sum(allPeriods().flatMap(x=>x.period.debtPayments.filter(p=>debtById(x,p.debtId)?.scope==='business'&&p.source==='business').map(p=>p.amount)))}
function businessFreeNow(){return businessCashNow()-Math.max(0,businessOperatingBalance())-Math.max(0,businessTaxBalance())-Math.max(0,businessDevelopmentBalance())-Math.max(0,businessDueTotal())-Math.max(0,businessDebtRemainingPlan(activeView()))}
function businessFixedPayment(itemId,pid=state.activePeriod.id){return state.business.fixedPayments.find(x=>x.itemId===itemId&&x.periodId===pid)}
function businessFixedPlan(){return sum(state.business.fixedItems.filter(x=>x.active).map(x=>x.amount))}
function businessFixedPaid(pid=state.activePeriod.id){return sum(state.business.fixedPayments.filter(x=>x.periodId===pid).map(x=>x.amount))}
function findPeriodById(pid){if(state.activePeriod.id===pid)return state.activePeriod;const a=state.archives.find(x=>x.period.id===pid);return a?.period||null}
function setEditable(on){document.querySelectorAll('.editable,[data-add-fixed],[data-edit-fixed],[data-delete-fixed],[data-toggle-active],[data-toggle-paid],[data-spend],[data-edit-tx],[data-delete-tx],[data-pay-debt],[data-edit-debt],[data-delete-debt]').forEach(el=>el.disabled=!on);$('#settingsBtn').disabled=!on;$('#restoreBtn').disabled=!on}
